### ISSUE TITLE
Incompatible With MSSQL Driver 8.2.2??

### ISSUE THREAD

**Issue by devmanhinton** [Azure/azure-sqldb-spark#76]
Please close this if I am wrong. ReadMe notes this works with mssql driver 6.2+

<img width="662" alt="Screen Shot 2020-05-08 at 11 30 31 AM" src="https://user-images.githubusercontent.com/1439051/81424824-884fc200-9124-11ea-9620-78ba3f751cb4.png">

Ran with 8.2.2.jre8 and ran into

```
java.lang.NoSuchMethodError: com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeToServer(Lcom/microsoft/sqlserver/jdbc/ISQLServerBulkRecord;)V
	at com.microsoft.azure.sqldb.spark.connect.DataFrameFunctions.com$microsoft$azure$sqldb$spark$connect$DataFrameFunctions$$bulkCopy(DataFrameFunctions.scala:127)
	at com.microsoft.azure.sqldb.spark.connect.DataFrameFunctions$$anonfun$bulkCopyToSqlDB$1.apply(DataFrameFunctions.scala:72)
```

Downgraded to `7.4.1.jre8` and it works

**Comment by arvindshmicrosoft** [comment]
Thank you @devmanhinton for your interest and efforts to document your issue. Given the 8.2 release JDBC release is relatively new, I am not aware of any testing that was done with that driver version. So I will close this issue with a promise to update the README to reflect this limitation.

Also, consider evaluating the 
[Apache Spark Connector for SQL Server and Azure SQL](https://github.com/microsoft/sql-spark-connector) which is a newer connector. That connector improves the experience around bulk load, and adds other improvements like Python and R bindings etc. However at this time I am not sure about the supportability for MSSQL JDBC 8.2.2 in that connector, either.
